# Stores the 'global' arguments for the repository

project:
    name: RainbowK3d
    version: 0.1.0
    author: VOYEUX Alfred
    description: "3D visualisation and re-projection of a solar protuberance"
    
directories:
    data: &datapath data
    fake_data: &fakepath !join [*datapath, "fake_data"]
    fusion_data: &fusionpath !join [*datapath, "fusion_data"]
    animation: &animationpath animation
    projection: &projectionpath projection
    manual_tests: &manualtestspath manual_tests
    tests: &testspath tests
    sdo: &sdopath !join ['..', 'sdo']

    save:
        path: &workdone !join ['..', 'work_done']  # ! this is wrong for now
        envelope: !join [*workdone, 'envelope']

data: 
    path:
        real: !join [*datapath, "data.h5"]
        fake: !join [*fakepath, "fake_from_toto.h5"]
        fusion: !join [*fusionpath, "data_with_fake_from_toto.h5"]
        tests: !join [*manualtestspath, "testing_tests.h5"]

processes: 4

debug:
    tests: True  # ! need to implement this somewhere
    processes: 10
    verbose: 1
    flush: True
