# Stores the 'global' arguments for the repository

# todo need to think properly about the structure of the config file

project:
    name: RainbowK3d
    version: 0.1.0
    author: VOYEUX Alfred
    description: "3D visualisation and re-projection of a solar protuberance"
    
paths:
    data: 
        real: data/data.h5
        fake: data/fake_data/fake_from_toto.h5
        tests: manual_tests/testing_tests.h5
    animation: animation
    projection: projection
    tests: tests

processes: 4

debug:
    tests: True  # ! need to implement this somewhere
    processes: 10
    verbose: 1
    flush: True
