# Stores the 'global' arguments for the repository

project:
    name: RainbowK3d
    version: 0.1.0
    author: VOYEUX Alfred
    description: "3D visualisation and re-projection of a solar protuberance"

path:
    dir:
        code:
            path: &pathcode codes

            animation: !join [*pathcode, 'animation']
            projection: !join [*pathcode, 'projection']
            manual_test: !join [*pathcode, 'manual_tests']
            test: !join [*pathcode, 'tests'] 

            data: &datacode !join [*pathcode, 'data']
            fake_data: !join [*datacode, 'fake_data']
            fusion_data: !join [*datacode, 'fusion_data']
            quick_data: !join [*datacode, 'quick_visualisation_data']

        data: 
            path: &datapath data_files

            hdf5: &datahdf5 !join [*datapath, 'hdf5_files']
            mp4: !join [*datapath, 'mp4_saves']
            synoptic_maps: !join [*datapath, 'synoptic_maps']  # ! subdirectories are not given here
            sdo: !join [*datapath, 'sdo']

            cubes:
                path: &datacubes !join [*datapath, 'cubes']

                karine: !join [*datacubes, 'karine']
                alfred: !join [*datacubes, 'alfred']
                fake: !join [*datacubes, 'save_from_toto']

            stereo: 
                path: &stereofiles !join [*datapath, 'stereo']

                avg: !join [*stereofiles, 'avg']
                int: !join [*stereofiles, 'int']

                mask:
                    alf: !join [*stereofiles, 'masque']
                    karine: !join [*stereofiles, 'masque_karine']

            fake:
                path: &fakedir !join [*datapath, 'fake_data']

                png: !join [*fakedir, 'png']
                fits: !join [*fakedir, 'fits']
                from_toto: !join [*fakedir, 'save_from_toto']

            result:
                path: &workdone !join [*datapath, 'work_done']

                contours: !join [*workdone, 'contours_3images']
                stereo: !join [*workdone, 'opening_stereo_new']
                envelope: !join [*workdone, 'envelope']
                texture: !join [*workdone, 'textures']
                projection: !join [*workdone, 'projection']

                stats: 
                    path: &stats !join [*workdone, 'stats']

                    plot: !join [*stats, 'stats_plot']

    data:
        stereob_info: !join [*datacubes, 'rainbow_stereob_304.save']

        real: !join [*datahdf5, 'data.h5']
        fake: !join [*datahdf5, 'fake_from_toto.h5']
        fusion: !join [*datahdf5, 'data_with_fake_from_toto.h5']

        test: !join [*datahdf5, 'testing.h5']

run:
    processes: 4
    verbose: 3

    debug:
        tests: True  # ! need to implement this somewhere
        processes: 10
        verbose: 1
        flush: True
